export const COMPOSITION_WIN_RATES: Record<string, number> = {
  "ELIM_SPECIALIST,ELIM_SPECIALIST,ELIM_SPECIALIST": 0.616,
  "ELIM_SPECIALIST,ELIM_SPECIALIST,WART_SPECIALIST": 0.581,
  "WART_SPECIALIST,WART_SPECIALIST,WART_SPECIALIST": 0.566,
  "ELIM_SPECIALIST,WART_SPECIALIST,WART_SPECIALIST": 0.561,
  "BALANCED,WART_SPECIALIST,WART_SPECIALIST": 0.560,
  "BALANCED,BALANCED,WART_SPECIALIST": 0.547,
  "BALANCED,ELIM_SPECIALIST,WART_SPECIALIST": 0.544,
  "BALANCED,ELIM_SPECIALIST,ELIM_SPECIALIST": 0.533
};

export const MATCHUP_WIN_RATES: Record<string, number> = {
  "ELIM_SPECIALIST,ELIM_SPECIALIST,WART_SPECIALIST|BALANCED,BALANCED,GACHA_SPECIALIST": 0.791,
  "BALANCED,ELIM_SPECIALIST,WART_SPECIALIST|BALANCED,BALANCED,BALANCED": 0.789,
  "ELIM_SPECIALIST,ELIM_SPECIALIST,WART_SPECIALIST|BALANCED,GACHA_SPECIALIST,GACHA_SPECIALIST": 0.774,
  "WART_SPECIALIST,WART_SPECIALIST,WART_SPECIALIST|GACHA_SPECIALIST,GACHA_SPECIALIST,WART_SPECIALIST": 0.750,
  "ELIM_SPECIALIST,WART_SPECIALIST,WART_SPECIALIST|GACHA_SPECIALIST,GACHA_SPECIALIST,GACHA_SPECIALIST": 0.727,
  "ELIM_SPECIALIST,WART_SPECIALIST,WART_SPECIALIST|BALANCED,GACHA_SPECIALIST,GACHA_SPECIALIST": 0.718,
  "WART_SPECIALIST,WART_SPECIALIST,WART_SPECIALIST|ELIM_SPECIALIST,GACHA_SPECIALIST,GACHA_SPECIALIST": 0.714,
  "ELIM_SPECIALIST,ELIM_SPECIALIST,ELIM_SPECIALIST|BALANCED,GACHA_SPECIALIST,WART_SPECIALIST": 0.714
};
